name: GitHub Actions Demo
on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths-ignore: 
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: "* * * * 0"
  
